spring:
  application:
    name: "SpringPizzaOrderHandler"
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  profiles:
    active: "pizza"
