spring:
  application:
    name: "SpringPizzaOrderHandler"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  profiles:
    active: "pizza"

server:
  port: 8081
